/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsImageconvertRouteImport } from './routes/scripts/imageconvert'
import { Route as PhotosPublicIdRouteImport } from './routes/photos_/$publicId'

const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsImageconvertRoute = ScriptsImageconvertRouteImport.update({
  id: '/scripts/imageconvert',
  path: '/scripts/imageconvert',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPublicIdRoute = PhotosPublicIdRouteImport.update({
  id: '/photos_/$publicId',
  path: '/photos/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photos': typeof PhotosRoute
  '/photos/$publicId': typeof PhotosPublicIdRoute
  '/scripts/imageconvert': typeof ScriptsImageconvertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photos': typeof PhotosRoute
  '/photos/$publicId': typeof PhotosPublicIdRoute
  '/scripts/imageconvert': typeof ScriptsImageconvertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/photos': typeof PhotosRoute
  '/photos_/$publicId': typeof PhotosPublicIdRoute
  '/scripts/imageconvert': typeof ScriptsImageconvertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/photos' | '/photos/$publicId' | '/scripts/imageconvert'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photos' | '/photos/$publicId' | '/scripts/imageconvert'
  id:
    | '__root__'
    | '/'
    | '/photos'
    | '/photos_/$publicId'
    | '/scripts/imageconvert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotosRoute: typeof PhotosRoute
  PhotosPublicIdRoute: typeof PhotosPublicIdRoute
  ScriptsImageconvertRoute: typeof ScriptsImageconvertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/imageconvert': {
      id: '/scripts/imageconvert'
      path: '/scripts/imageconvert'
      fullPath: '/scripts/imageconvert'
      preLoaderRoute: typeof ScriptsImageconvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos_/$publicId': {
      id: '/photos_/$publicId'
      path: '/photos/$publicId'
      fullPath: '/photos/$publicId'
      preLoaderRoute: typeof PhotosPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotosRoute: PhotosRoute,
  PhotosPublicIdRoute: PhotosPublicIdRoute,
  ScriptsImageconvertRoute: ScriptsImageconvertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
