/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as ScriptsImageConvertRouteImport } from './routes/scripts/image-convert'
import { Route as ScriptsContactSheetRouteImport } from './routes/scripts/contact-sheet'
import { Route as ScriptsSplatRouteImport } from './routes/scripts/$'
import { Route as PhotosPublicIdRouteImport } from './routes/photos/$publicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsImageConvertRoute = ScriptsImageConvertRouteImport.update({
  id: '/scripts/image-convert',
  path: '/scripts/image-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsContactSheetRoute = ScriptsContactSheetRouteImport.update({
  id: '/scripts/contact-sheet',
  path: '/scripts/contact-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsSplatRoute = ScriptsSplatRouteImport.update({
  id: '/scripts/$',
  path: '/scripts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPublicIdRoute = PhotosPublicIdRouteImport.update({
  id: '/$publicId',
  path: '/$publicId',
  getParentRoute: () => PhotosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photos/$publicId': typeof PhotosPublicIdRoute
  '/scripts/$': typeof ScriptsSplatRoute
  '/scripts/contact-sheet': typeof ScriptsContactSheetRoute
  '/scripts/image-convert': typeof ScriptsImageConvertRoute
  '/photos/': typeof PhotosIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photos/$publicId': typeof PhotosPublicIdRoute
  '/scripts/$': typeof ScriptsSplatRoute
  '/scripts/contact-sheet': typeof ScriptsContactSheetRoute
  '/scripts/image-convert': typeof ScriptsImageConvertRoute
  '/photos': typeof PhotosIndexRoute
  '/scripts': typeof ScriptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/photos/$publicId': typeof PhotosPublicIdRoute
  '/scripts/$': typeof ScriptsSplatRoute
  '/scripts/contact-sheet': typeof ScriptsContactSheetRoute
  '/scripts/image-convert': typeof ScriptsImageConvertRoute
  '/photos/': typeof PhotosIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/photos/$publicId'
    | '/scripts/$'
    | '/scripts/contact-sheet'
    | '/scripts/image-convert'
    | '/photos/'
    | '/scripts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/photos/$publicId'
    | '/scripts/$'
    | '/scripts/contact-sheet'
    | '/scripts/image-convert'
    | '/photos'
    | '/scripts'
  id:
    | '__root__'
    | '/'
    | '/photos/$publicId'
    | '/scripts/$'
    | '/scripts/contact-sheet'
    | '/scripts/image-convert'
    | '/photos/'
    | '/scripts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScriptsSplatRoute: typeof ScriptsSplatRoute
  ScriptsContactSheetRoute: typeof ScriptsContactSheetRoute
  ScriptsImageConvertRoute: typeof ScriptsImageConvertRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/image-convert': {
      id: '/scripts/image-convert'
      path: '/scripts/image-convert'
      fullPath: '/scripts/image-convert'
      preLoaderRoute: typeof ScriptsImageConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/contact-sheet': {
      id: '/scripts/contact-sheet'
      path: '/scripts/contact-sheet'
      fullPath: '/scripts/contact-sheet'
      preLoaderRoute: typeof ScriptsContactSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$': {
      id: '/scripts/$'
      path: '/scripts/$'
      fullPath: '/scripts/$'
      preLoaderRoute: typeof ScriptsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$publicId': {
      id: '/photos/$publicId'
      path: '/$publicId'
      fullPath: '/photos/$publicId'
      preLoaderRoute: typeof PhotosPublicIdRouteImport
      parentRoute: typeof PhotosRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScriptsSplatRoute: ScriptsSplatRoute,
  ScriptsContactSheetRoute: ScriptsContactSheetRoute,
  ScriptsImageConvertRoute: ScriptsImageConvertRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
