/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesYpaRouteImport } from './routes/experiences/ypa'
import { Route as ExperiencesOutcomesRouteImport } from './routes/experiences/outcomes'
import { Route as ExperiencesFstlogisticsRouteImport } from './routes/experiences/fstlogistics'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesYpaRoute = ExperiencesYpaRouteImport.update({
  id: '/experiences/ypa',
  path: '/experiences/ypa',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesOutcomesRoute = ExperiencesOutcomesRouteImport.update({
  id: '/experiences/outcomes',
  path: '/experiences/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesFstlogisticsRoute = ExperiencesFstlogisticsRouteImport.update({
  id: '/experiences/fstlogistics',
  path: '/experiences/fstlogistics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/photos': typeof PhotosRoute
  '/references': typeof ReferencesRoute
  '/resume': typeof ResumeRoute
  '/experiences/fstlogistics': typeof ExperiencesFstlogisticsRoute
  '/experiences/outcomes': typeof ExperiencesOutcomesRoute
  '/experiences/ypa': typeof ExperiencesYpaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/photos': typeof PhotosRoute
  '/references': typeof ReferencesRoute
  '/resume': typeof ResumeRoute
  '/experiences/fstlogistics': typeof ExperiencesFstlogisticsRoute
  '/experiences/outcomes': typeof ExperiencesOutcomesRoute
  '/experiences/ypa': typeof ExperiencesYpaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/photos': typeof PhotosRoute
  '/references': typeof ReferencesRoute
  '/resume': typeof ResumeRoute
  '/experiences/fstlogistics': typeof ExperiencesFstlogisticsRoute
  '/experiences/outcomes': typeof ExperiencesOutcomesRoute
  '/experiences/ypa': typeof ExperiencesYpaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/photos'
    | '/references'
    | '/resume'
    | '/experiences/fstlogistics'
    | '/experiences/outcomes'
    | '/experiences/ypa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/photos'
    | '/references'
    | '/resume'
    | '/experiences/fstlogistics'
    | '/experiences/outcomes'
    | '/experiences/ypa'
  id:
    | '__root__'
    | '/'
    | '/photos'
    | '/references'
    | '/resume'
    | '/experiences/fstlogistics'
    | '/experiences/outcomes'
    | '/experiences/ypa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhotosRoute: typeof PhotosRoute
  ReferencesRoute: typeof ReferencesRoute
  ResumeRoute: typeof ResumeRoute
  ExperiencesFstlogisticsRoute: typeof ExperiencesFstlogisticsRoute
  ExperiencesOutcomesRoute: typeof ExperiencesOutcomesRoute
  ExperiencesYpaRoute: typeof ExperiencesYpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/ypa': {
      id: '/experiences/ypa'
      path: '/experiences/ypa'
      fullPath: '/experiences/ypa'
      preLoaderRoute: typeof ExperiencesYpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/outcomes': {
      id: '/experiences/outcomes'
      path: '/experiences/outcomes'
      fullPath: '/experiences/outcomes'
      preLoaderRoute: typeof ExperiencesOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/fstlogistics': {
      id: '/experiences/fstlogistics'
      path: '/experiences/fstlogistics'
      fullPath: '/experiences/fstlogistics'
      preLoaderRoute: typeof ExperiencesFstlogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhotosRoute: PhotosRoute,
  ReferencesRoute: ReferencesRoute,
  ResumeRoute: ResumeRoute,
  ExperiencesFstlogisticsRoute: ExperiencesFstlogisticsRoute,
  ExperiencesOutcomesRoute: ExperiencesOutcomesRoute,
  ExperiencesYpaRoute: ExperiencesYpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
